# Generated by Django 3.1.2 on 2020-10-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=32)),
                ('person1_id', models.CharField(max_length=100)),
                ('person2_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='person_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
