# Generated by Django 3.1.2 on 2020-10-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0002_auto_20201003_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='person_id',
        ),
    ]
