# Generated by Django 3.1.2 on 2020-10-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0003_remove_user_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personalid',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='person1_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='contact',
            name='person2_id',
            field=models.CharField(max_length=128),
        ),
    ]
