# Generated by Django 3.1.2 on 2020-10-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0004_auto_20201003_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='personalid',
            new_name='personal_id',
        ),
    ]
