# Generated by Django 3.1.2 on 2020-10-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0006_auto_20201029_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='personal_id',
        ),
    ]
