# Generated by Django 3.1.2 on 2020-11-01 11:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('researcher', '0007_remove_user_personal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=12)),
                ('age', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NA', 'Unknown')], default='NA', max_length=2)),
                ('location', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('address', models.CharField(max_length=16)),
                ('test_result', models.CharField(choices=[('True', 'Positive'), ('False', 'Negative'), ('None', 'Unknown')], default='None', max_length=5)),
                ('encryption_keys', models.TextField(blank=True, null=True)),
                ('cluster_id', models.IntegerField(default=0)),
                ('relate', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='k_user',
            name='cluster_id',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
