# Generated by Django 3.1.2 on 2020-11-01 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0008_auto_20201101_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='k_user',
            old_name='age',
            new_name='age_max',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='relate',
        ),
        migrations.AddField(
            model_name='k_user',
            name='age_min',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
