# Generated by Django 3.1.2 on 2020-11-01 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0009_auto_20201101_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='k_user',
            name='age',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
